import DemandPrediction from '../models/DemandPrediction.js';
import { asyncHandler, success } from '../utils/response.js';
import { getDemandPredictions, localForecast, classifyRisk } from '../services/predictionService.js';
import { getAvailableStock } from '../services/inventoryService.js';

export const predict = asyncHandler(async (req, res) => {
  const { forecastDays = 14, historyDays = 90, forceRefresh = false } = req.body;
  const result = await getDemandPredictions({
    forecastDays: Number(forecastDays),
    historyDays: Number(historyDays),
    forceRefresh: Boolean(forceRefresh),
  });
  return success(res, result.predictions, 'OK', { source: result.source, forecastDays });
});

export const oneOff = asyncHandler(async (req, res) => {
  const { bloodGroup, historicalData, forecastPeriod = 14 } = req.body;
  if (!Array.isArray(historicalData)) return res.status(400).json({ success: false, message: 'historicalData must be an array', errorCode: 'INVALID_INPUT' });
  const { predicted, model, dataPoints } = localForecast(historicalData, Number(forecastPeriod));
  const stock = await getAvailableStock();
  const risk = classifyRisk(stock[bloodGroup] ?? 0, predicted);
  return success(res, {
    bloodGroup,
    predictedDemand: predicted,
    forecastPeriod: Number(forecastPeriod),
    currentStock: stock[bloodGroup] ?? 0,
    riskLevel: risk,
    model,
    dataPoints,
    disclaimer: 'Forecast generated by a statistical heuristic; not a medically validated prediction.',
  });
});

export const historySeries = asyncHandler(async (_req, res) => {
  const items = await DemandPrediction.find({}).sort({ periodEnd: -1 }).limit(100).lean();
  return success(res, items);
});

export const trends = asyncHandler(async (_req, res) => {
  const { default: Donation } = await import('../models/Donation.js');
  const { default: EmergencyRequest } = await import('../models/EmergencyRequest.js');
  const since = new Date(Date.now() - 180 * 24 * 3600 * 1000);

  const [monthlyDonations, monthlyRequests] = await Promise.all([
    Donation.aggregate([
      { $match: { donationDate: { $gte: since }, status: 'completed' } },
      { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$donationDate' } }, units: { $sum: '$units' }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]),
    EmergencyRequest.aggregate([
      { $match: { createdAt: { $gte: since } } },
      { $group: { _id: { $dateToString: { format: '%Y-%m', date: '$createdAt' } }, units: { $sum: '$requiredUnits' }, count: { $sum: 1 } } },
      { $sort: { _id: 1 } },
    ]),
  ]);

  const demandByGroup = await EmergencyRequest.aggregate([
    { $match: { createdAt: { $gte: since } } },
    { $group: { _id: '$bloodGroup', units: { $sum: '$requiredUnits' }, requests: { $sum: 1 } } },
    { $sort: { units: -1 } },
  ]);

  return success(res, { monthlyDonations, monthlyRequests, demandByGroup });
});

export default { predict, oneOff, historySeries, trends };
